### ISSUE TITLE
a lot of conv alternatives

### ISSUE THREAD

**Issue by iperov** [brohrer/sharpened-cosine-similarity#17]
there a lot of conv alternatives last 5 years
why do ppl still using vanilla conv ?

**Comment by 4rtemi5** [comment]
Mostly due to the [hardware lottery](https://arxiv.org/abs/2009.06489). A software idea wins if it is superior on the current hardware, which in turn has been optimized for the current software and vice versa.  
This is a system that favors the status quo over hypothetical improvements that could be reached if both hardware and software could jointly be adapted to some new idea.

Hope that answers your question.
